// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzPuNNBWjlCFiRCFKuR0_0rh0GlFeVfSc',
    appId: '1:658114513459:web:0dd104dc777b03b5073146',
    messagingSenderId: '658114513459',
    projectId: 'flutter18-9bfed',
    authDomain: 'flutter18-9bfed.firebaseapp.com',
    storageBucket: 'flutter18-9bfed.appspot.com',
    measurementId: 'G-9PDMX9YCQT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACG4DhNON5ippY45OVGNEmo5jbGuY8-QE',
    appId: '1:658114513459:android:5332b658030638ff073146',
    messagingSenderId: '658114513459',
    projectId: 'flutter18-9bfed',
    storageBucket: 'flutter18-9bfed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDJbdfwcaPZjrKF3noJxUynNP2K9AoVQE',
    appId: '1:658114513459:ios:d77593ade05bfa29073146',
    messagingSenderId: '658114513459',
    projectId: 'flutter18-9bfed',
    storageBucket: 'flutter18-9bfed.appspot.com',
    iosClientId: '658114513459-m2bu60t2higu3ba5k56j8kg5e2ls0unf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDJbdfwcaPZjrKF3noJxUynNP2K9AoVQE',
    appId: '1:658114513459:ios:d77593ade05bfa29073146',
    messagingSenderId: '658114513459',
    projectId: 'flutter18-9bfed',
    storageBucket: 'flutter18-9bfed.appspot.com',
    iosClientId: '658114513459-m2bu60t2higu3ba5k56j8kg5e2ls0unf.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
